### ISSUE TITLE
bug: 【api网关】权限管理-应用权限导出的应用权限，在Excel内中文显示乱码

### ISSUE THREAD

**Issue by linxiaowu1992** [TencentBlueKing/blueking-apigateway#107]
### Current Behavior

![image](https://github.com/TencentBlueKing/blueking-apigateway/assets/29301212/84aa4609-fae6-4c78-bcaa-28b27898bcee)
如图，应用权限导出后，在excel中打开，中文会乱码。在txt或者wps中打开是正常的

### Steps to Reproduce

1、进入到API网关-应用权限
2、导出
![image](https://github.com/TencentBlueKing/blueking-apigateway/assets/29301212/84df6af9-2a27-49b4-a2f5-d5027fd1a561)

### Version and Environment

- 蓝鲸版本号 (the version of BlueKing platform): V1.10.0-beta.4
- 容器化部署还是二进制部署 (deployed on Kubernetes or using binary files):容器化
- 二进制部署请提供网关版本号 (the version of bk-apigateway, required for binary distribution):
- 容器化部署请提供 (provide the following information, required for Kubernetes helm chart distribution):
  - bk-apigateway helm chart version:bk-apigateway-1.10.0-beta.5-cw
  - `values.yaml` 中是否做了修改 (whether you have modified the `values.yaml`): 否
  - `values.yaml` 中的配置, 注意去除敏感信息 (the contents of the `values.yaml` file, remember to remove any sensitive information):

**Comment by wklken** [comment]
默认下载的utf-8的csv文件 => 如果其他软件打开正常, excel打开有问题, 先看下excel的配置? (mac 下excel/numbers/textedit等打开都正常
