### ISSUE TITLE
API 网关：如何添加自定义编码组件

### ISSUE THREAD

**Issue by alex-smile** [TencentBlueKing/blueking-apigateway#254]
### Description

不同的版本，有不同的处理方案。先获取服务版本号（容器化 chart version，二进制 app version），再根据版本号找对应的方案进行处理。

## 容器化版本

- 1. chart README.md 常见问题中，`2. 如何导入自定义编码组件` 部分有介绍，请参考，将组件代码添加到容器
- 2. 在网关管理端 -> 组件管理中，新建组件

## 二进制版本（新版二进制版本，将默认使用旧版 open-paas/esb 服务，请检查链路确认）

在 ESB 项目的 `components/generic/apis` 目录下，将组件代码 copy 到此目录下，并创建对应的组件。

## 旧版二进制版本 (open-paas/esb)
- 在 ESB 项目的 `components/generic/apis` 目录下，将组件代码 copy 到此目录下，并创建对应的组件。

**Comment by wklken** [comment]
容器化，参考 helm chart bk-apigateway 的 README.md
